# Generated by Django 3.1.4 on 2020-12-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
